### ISSUE TITLE
Upload Folder isn't working.

### ISSUE THREAD

**Issue by nickchen120235** [filebrowser/filebrowser#1096]
Hi, I just started a server using the official docker image and docker-compose with an apache reverse proxy on Ubuntu 20.04.
I encounted errors when trying to upload the whole folder, while uploading single file works.
![image](https://user-images.githubusercontent.com/45678482/94264949-4061f800-ff6a-11ea-9c79-a2ae63682a19.png)
My `virtualhost.conf`
```conf
<VirtualHost *:443>
  ServerName my.server.com
  Protocols h2 http/1.1

  SSLEngine on
  SSLCertificateFile    /etc/letsencrypt/live/my.server.com/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/my.server.com/privkey.pem

  # SSLProxyEngine on
  ProxyPass "/" "http://localhost:8002/"
  ProxyPassReverse "/" "http://localhost:8002/"
  ProxyPreserveHost on
</VirtualHost>
```
My `docker-compose.yml`
```yaml
version: '3.8'

services:
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - /etc/filebrowser/database.db:/database.db # database
      - ~/files:/srv                              # root
    restart: always
    ports:
      - '127.0.0.1:8002:80'
```
Using the default config file for docker.

**Comment by o1egl** [comment]
1. Can you try to use filebrowser directly?
2. Which browser are you using?

**Comment by nickchen120235** [comment]
@o1egl Thank you for replying!
> 1. Can you try to use filebrowser directly?

Starting up a server using command `filebrowser -r ~/files -a 0.0.0.0`
The "Upload Folder" function is working correctly.

> 2. Which browser are you using?

Chrome 85.0.4183.121
Firefox 81.0
![image](https://user-images.githubusercontent.com/45678482/94419503-78a94680-01b5-11eb-925e-b8f093e04127.png)
Both on Windows 10 Home 1903

**Comment by o1egl** [comment]
So, the problem is then in the proxy config. I guess the issue is in http2. Try to remove this option.

**Comment by ramiresviana** [comment]
https://github.com/filebrowser/filebrowser/blob/1529e796df86e6245e107dabe512fa1841f9d4da/frontend/src/utils/upload.js#L103-L108

The file path is encoded when uploading multiple files, which cause the separator '/' to be encoded too. Filebrowser itself handles the request with no problem, using a proxy causes problems with the path. This is an frontend issue and should be fixed.

**Comment by nickchen120235** [comment]
@o1egl I changed the `Protocols` part to `Protocols http/1.1` and it still doesn't work.
@ramiresviana So I guess it's a bug?

**Comment by nambrosch** [comment]
I can't imagine http/2 would matter here, could you take a har of a page load?

Also, don't forget to upgrade your websocket requests:
```
  RewriteEngine On
  RewriteCond %{HTTP:Connection} Upgrade [NC]
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteRule (.*) ws://127.0.0.1:8080/$1 [P,L]
```

**Comment by nickchen120235** [comment]
@nambrosch 
[HAR with original settings](https://drive.google.com/file/d/1TOA_THQDtk_oWfMjVj7INJzbMne9ZfJQ/view?usp=sharing)
[HAR with RewriteEngine](https://drive.google.com/file/d/1_mVjXpNdq9Tu2V8mIdI6xznWfKLZlcNr/view?usp=sharing)

**Comment by nambrosch** [comment]
`POST /api/resources/teset%2Ftest1.txt?override=false` is returning a 404, could you click the "disable cache" checkbox in the inspector and do a force reload, then send that capture?  I want to see if there are any other failed objects or if that's really the only one.

**Comment by ramiresviana** [comment]
@nickchen120235 be careful when providing browser requests, it can have sensitive information that you are not willing to share, like tokens and domains.

**Comment by nickchen120235** [comment]
@nambrosch [new har](https://drive.google.com/file/d/1uWVUjka1iGLmGqex-eCYdVA3RdCZsp2C/view?usp=sharing)

**Comment by nambrosch** [comment]
Thanks for the har, @nickchen120235 - I can confirm these running through my own apache mod_proxy setup as well.

Uploading a single file is a success, here is the request:
```
POST https://foo.bar/filebrowser/api/resources/file.txt?override=false (200)
```

Uploading a folder by dragging onto the browser window creates the folder but the files fail to upload:
```
POST https://foo.bar/filebrowser/api/resources/folder/?override=false
POST https://foo.bar/filebrowser/api/resources/folder%2Ffile.txt?override=false
```

I believe the frontend is encoding the last forward slash to `%2F` - this happens before the request reaches the web server so I would presume it's unrelated to the proxy.

@ramiresviana Can you ensure that `url` is being encoded properly?

https://github.com/filebrowser/filebrowser/search?q=encodeRFC5987ValueChars&type=code
https://github.com/filebrowser/filebrowser/search?q=encodeURIComponent&type=code
