### ISSUE TITLE
[BUG] Web video playback controls are hidden by default on latest release

### ISSUE THREAD

**Issue by phere-x** [filebrowser/filebrowser#3755]
After updating to the lates release, opening a video shows no video playback controls by default, requiring me to manually right-click and select "Show all controls", which isn't persistent and so I have to repeat it each time.

Reverted back to `v2.31.2-s6` version as it doesn't have this issue.

Tested on latest Chrome & Edge browser versions.

**Comment by KoenM9264** [comment]
I have the same issue

**Comment by RayOei** [comment]
Maybe solved with #3742

**Comment by amrojjeh** [comment]
Same issue here. Tested with Edge and Firefox

**Comment by xiaokaixuan** [comment]
https://github.com/xiaokaixuan/filebrowser/releases/tag/v2.32.0

1. Fix issue.
2. Enable keyboard fast forward and rewind.

**Comment by D99-1** [comment]
Not fixed on my end.

V2.32.0, MacOS

Tested on: Chrome & Arc

**Comment by D99-1** [comment]
Issue still exists on my end.

V2.32.0
MacOS: Chrome & Arc

**Comment by kenjitoyama** [comment]
Not fixed on filebrowser V2.32.0 on Windows Chrome (135.0.7049.42), Android Chrome (135.0.7049.79) and Android Firefox (137.0 build # 2016081319). On mobile, I can't even enable the controls via a long click, and in Android Chrome it's particularly bad because the only option is to "Download video". On Android Firefox it at least lets me copy the URL link and then open it in a new tab where I can see the controls.

**Comment by walldodge** [comment]
Truenas app
v2.31.2 v1.2.5
Issue still persist. Rolled back to v2.31.2.

**Comment by walldodge** [comment]
Truenas app
v2.32.0_1.2.12
Issue still persist. Rolled back to v2.31.2.
